backend:
  name: git-gateway
  branch: main # Change if using another default branch

media_folder: "images/uploads" # Folder for uploaded images
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Electronics & Gadgets", "Home & Living", "Beauty & Personal Care", "Food & Beverages"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Affiliate Link", name: "link", widget: "string" }
