backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "src/content/products.json"
        label: "Products JSON"
        name: "products-json"
        fields:
          - name: "items"
            label: "Items"
            widget: "list"
            fields:
              - { name: "id", label: "ID", widget: "string" }
              - { name: "title", label: "Title", widget: "string" }
              - name: category
                label: Category
                widget: select
                options:
                  - "Electronics & Gadgets"
                  - "Home & Living"
                  - "Beauty & Personal Care"
                  - "Food & Beverages"
              - { name: "price", label: "Price", widget: "number" }
              - { name: "image", label: "Image", widget: "image" }
              - { name: "url", label: "Affiliate URL", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }